version: '3'
services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: lotto
      POSTGRES_USER: lotto
      POSTGRES_DB: lotto
    ports:
      - "5431:5432"
  app:
    image: lotto
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/lotto
      SPRING_DATASOURCE_USERNAME: lotto
      SPRING_DATASOURCE_PASSWORD: lotto
  localstack:
    image: localstack/localstack:0.12.12
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,serverless,sqs
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=application_default
      - HOSTNAME_EXTERNAL=localstack
      - DEBUG=1
    volumes:
      - "${PWD}/ls_tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


